![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/75165824-badf4680-5701-11ea-9c5b-5475b0a33abf.png"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Pandas - `DataFrame`s

Probably the most important data structure of pandas is the `DataFrame`. It's a tabular structure tightly integrated with `Series`.

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on!

In [1]:
import numpy as np
import pandas as pd

We'll keep our analysis of G7 countries and looking now at DataFrames. As said, a DataFrame looks a lot like a table (as the one you can appreciate [here](https://docs.google.com/spreadsheets/d/1IlorV2-Oh9Da1JAZ7weVw86PQrQydSMp-ydVMH135iI/edit?usp=sharing)):

<img width="700" src="https://user-images.githubusercontent.com/872296/38153492-72c032ca-3443-11e8-80f4-9de9060a5127.png" />

Creating `DataFrame`s manually can be tedious. 99% of the time you'll be pulling the data from a Database, a csv file or the web. But still, you can create a DataFrame by specifying the columns and values:

In [47]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
})

_(The `columns` attribute is optional. I'm using it to keep the same order as in the picture above)_

In [3]:
df

   Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

`DataFrame`s also have indexes. As you can see in the "table" above, pandas has assigned a numeric, autoincremental index automatically to each "row" in our DataFrame. In our case, we know that each row represents a country, so we'll just reassign the index:

In [50]:
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [5]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [6]:
df.columns

Index(['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'], dtype='object')

In [7]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Population    7 non-null      float64
 1   GDP           7 non-null      int64
 2   Surface Area  7 non-null      int64
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object
dtypes: float64(2), int64(2), object(1)
memory usage: 336.0+ bytes

In [9]:
df.size

35

In [10]:
df.shape

(7, 5)

In [11]:
df[['Population', 'Continent']].describe()

       Population
count    7.000000
mean   107.302571
std     97.249970
min     35.467000
25%     62.308000
50%     64.511000
75%    104.000500
max    318.523000

In [12]:
df.dtypes

Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [13]:
df.dtypes.value_counts()

float64    2
int64      2
object     1
Name: count, dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing, Selection and Slicing

Individual columns in the DataFrame can be selected with regular indexing. Each column is represented as a `Series`:

In [14]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [15]:
df.loc['France'].to_frame()

               France
Population     63.951
GDP           2833687
Surface Area   640679
HDI             0.888
Continent      Europe

In [16]:
df.loc['Canada':'France']

        Population      GDP  Surface Area    HDI Continent
Canada      35.467  1785387       9984670  0.913   America
France      63.951  2833687        640679  0.888    Europe

In [17]:
df.iloc[2:4]

         Population      GDP  Surface Area    HDI Continent
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

In [18]:
df['Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

Note that the `index` of the returned Series is the same as the DataFrame one. And its `name` is the name of the column. If you're working on a notebook and want to see a more DataFrame-like format you can use the `to_frame` method:

In [19]:
df['Population'].to_frame()

                Population
Canada              35.467
France              63.951
Germany             80.940
Italy               60.665
Japan              127.061
United Kingdom      64.511
United States      318.523

Multiple columns can also be selected similarly to `numpy` and `Series`:

In [20]:
df[['Population', 'GDP']]

                Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In this case, the result is another `DataFrame`. Slicing works differently, it acts at "row level", and can be counter intuitive:

In [21]:
df[1:3]

         Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

Row level selection works better with `loc` and `iloc` **which are recommended** over regular "direct slicing" (`df[:]`).

`loc` selects rows matching the given index:

In [22]:
df.loc['Italy']

Population       60.665
GDP             2167744
Surface Area     301336
HDI               0.873
Continent        Europe
Name: Italy, dtype: object

In [23]:
df.loc['France': 'Italy']

         Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

As a second "argument", you can pass the column(s) you'd like to select:

In [24]:
df.loc['France': 'Italy', 'Population']

France     63.951
Germany    80.940
Italy      60.665
Name: Population, dtype: float64

In [25]:
df.loc['France': 'Italy', ['Population', 'GDP']]

         Population      GDP
France       63.951  2833687
Germany      80.940  3874437
Italy        60.665  2167744

`iloc` works with the (numeric) "position" of the index:

In [26]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [27]:
df.iloc[0]

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [28]:
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [29]:
df.iloc[[0, 1, -1]]

               Population       GDP  Surface Area    HDI Continent
Canada             35.467   1785387       9984670  0.913   America
France             63.951   2833687        640679  0.888    Europe
United States     318.523  17348075       9525067  0.915   America

In [30]:
df.iloc[1:3]

         Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

In [31]:
df.iloc[1:3, 3]

France     0.888
Germany    0.916
Name: HDI, dtype: float64

In [32]:
df.iloc[1:3, [0, 3]]

         Population    HDI
France       63.951  0.888
Germany      80.940  0.916

In [33]:
df.iloc[1:3, 1:3]

             GDP  Surface Area
France   2833687        640679
Germany  3874437        357114

> **RECOMMENDED: Always use `loc` and `iloc` to reduce ambiguity, specially with `DataFrame`s with numeric indexes.**

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Conditional selection (boolean arrays)

We saw conditional selection applied to `Series` and it'll work in the same way for `DataFrame`s. After all, a `DataFrame` is a collection of `Series`:

In [34]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [35]:
df['Population'] > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [36]:
df.loc[df['Population'] > 70]

               Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

The boolean matching is done at Index level, so you can filter by any row, as long as it contains the right indexes. Column selection still works as expected:

In [37]:
df.loc[df['Population'] > 70, 'Population']

Germany           80.940
Japan            127.061
United States    318.523
Name: Population, dtype: float64

In [38]:
df.loc[df['Population'] > 70, ['Population', 'GDP']]

               Population       GDP
Germany            80.940   3874437
Japan             127.061   4602367
United States     318.523  17348075

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dropping stuff

Opposed to the concept of selection, we have "dropping". Instead of pointing out which values you'd like to _select_ you could point which ones you'd like to `drop`:

In [51]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [39]:
df.drop('Canada')

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [54]:
cleaned_df = df.drop(['France', 'Japan'])

In [55]:
cleaned_df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [45]:
df.drop(columns=['Population', 'HDI'], inplace= True)

In [46]:
df

                     GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [56]:
df.drop(['Italy', 'Canada'], axis=0)

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [57]:
df.drop(['Population', 'HDI'], axis=1)

                     GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [58]:
df.drop(['Population', 'HDI'], axis=1)

                     GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [59]:
df.drop(['Population', 'HDI'], axis='columns')

                     GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [60]:
df.drop(['Canada', 'Germany'], axis='rows')

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

All these `drop` methods return a new `DataFrame`. If you'd like to modify it "in place", you can use the `inplace` attribute (there's an example below).

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Operations

In [61]:
df[['Population', 'GDP']]

                Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [62]:
df[['Population', 'GDP']] / 100

                Population        GDP
Canada             0.35467   17853.87
France             0.63951   28336.87
Germany            0.80940   38744.37
Italy              0.60665   21677.44
Japan              1.27061   46023.67
United Kingdom     0.64511   29500.39
United States      3.18523  173480.75

**Operations with Series** work at a column level, broadcasting down the rows (which can be counter intuitive).

In [63]:
crisis = pd.Series([-1_000_000, -0.3], index=['GDP', 'HDI'])
crisis

GDP   -1000000.0
HDI         -0.3
dtype: float64

In [64]:
df[['GDP', 'HDI']]

                     GDP    HDI
Canada           1785387  0.913
France           2833687  0.888
Germany          3874437  0.916
Italy            2167744  0.873
Japan            4602367  0.891
United Kingdom   2950039  0.907
United States   17348075  0.915

In [65]:
df[['GDP', 'HDI']] + crisis

                       GDP    HDI
Canada            785387.0  0.613
France           1833687.0  0.588
Germany          2874437.0  0.616
Italy            1167744.0  0.573
Japan            3602367.0  0.591
United Kingdom   1950039.0  0.607
United States   16348075.0  0.615

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Modifying DataFrames

It's simple and intuitive, You can add columns, or replace values for columns without issues:

### Adding a new column

In [76]:
langs = pd.Series(
    ['French', 'German', 'Italian'],
    index=['France', 'Germany', 'Italy'],
    name='Language'
)

In [77]:
langs

France      French
Germany     German
Italy      Italian
Name: Language, dtype: object

In [78]:
df['Language'] = langs

In [72]:
df['Capital'] = ['Toronto', 'Paris', 'Berlin', 'Rome', 'Tokyo', 'Washington DC', 'London']

In [73]:
df

,Population,GDP,Surface Area,HDI,Continent,Language,Capital
Canada,35.467,1785387,9984670,0.913,America,NaN,Toronto
France,63.951,2833687,640679,0.888,Europe,French,Paris
Germany,80.940,3874437,357114,0.916,Europe,German,Berlin
Italy,60.665,2167744,301336,0.873,Europe,Italian,Rome
Japan,127.061,4602367,377930,0.891,Asia,NaN,Tokyo
United Kingdom,64.511,2950039,242495,0.907,Europe,NaN,Washington DC
United States,318.523,17348075,9525067,0.915,America,NaN,London

---
### Replacing values per column

In [74]:
df['Language'] = 'English'

In [79]:
df

,Population,GDP,Surface Area,HDI,Continent,Language,Capital
Canada,35.467,1785387,9984670,0.913,America,NaN,Toronto
France,63.951,2833687,640679,0.888,Europe,French,Paris
Germany,80.940,3874437,357114,0.916,Europe,German,Berlin
Italy,60.665,2167744,301336,0.873,Europe,Italian,Rome
Japan,127.061,4602367,377930,0.891,Asia,NaN,Tokyo
United Kingdom,64.511,2950039,242495,0.907,Europe,NaN,Washington DC
United States,318.523,17348075,9525067,0.915,America,NaN,London

In [81]:
df.loc['Japan', 'Language'] = 'Japanese'

In [83]:
df.loc[['United Kingdom', 'United States'], 'Language'] = ['English', 'American English']

In [84]:
df

,Population,GDP,Surface Area,HDI,Continent,Language,Capital
Canada,35.467,1785387,9984670,0.913,America,NaN,Toronto
France,63.951,2833687,640679,0.888,Europe,French,Paris
Germany,80.940,3874437,357114,0.916,Europe,German,Berlin
Italy,60.665,2167744,301336,0.873,Europe,Italian,Rome
Japan,127.061,4602367,377930,0.891,Asia,Japanese,Tokyo
United Kingdom,64.511,2950039,242495,0.907,Europe,English,Washington DC
United States,318.523,17348075,9525067,0.915,America,American English,London

---
### Renaming Columns

In [85]:
df.rename(
    columns={
        'HDI': 'Human Development Index',
        'Anual Popcorn Consumption': 'APC'
    }, index={
        'United States': 'USA',
        'United Kingdom': 'UK',
        'Argentina': 'AR'
    })

,Population,GDP,Surface Area,Human Development Index,Continent,Language,Capital
Canada,35.467,1785387,9984670,0.913,America,NaN,Toronto
France,63.951,2833687,640679,0.888,Europe,French,Paris
Germany,80.940,3874437,357114,0.916,Europe,German,Berlin
Italy,60.665,2167744,301336,0.873,Europe,Italian,Rome
Japan,127.061,4602367,377930,0.891,Asia,Japanese,Tokyo
UK,64.511,2950039,242495,0.907,Europe,English,Washington DC
USA,318.523,17348075,9525067,0.915,America,American English,London

In [89]:
df.index.str.upper()

Index(['CANADA', 'FRANCE', 'GERMANY', 'ITALY', 'JAPAN', 'UNITED KINGDOM',
       'UNITED STATES'],
      dtype='object')

In [93]:
df

,Population,GDP,Surface Area,HDI,Continent,Language,Capital
CANADA,35.467,1785387,9984670,0.913,America,NaN,Toronto
FRANCE,63.951,2833687,640679,0.888,Europe,French,Paris
GERMANY,80.940,3874437,357114,0.916,Europe,German,Berlin
ITALY,60.665,2167744,301336,0.873,Europe,Italian,Rome
JAPAN,127.061,4602367,377930,0.891,Asia,Japanese,Tokyo
UNITED KINGDOM,64.511,2950039,242495,0.907,Europe,English,Washington DC
UNITED STATES,318.523,17348075,9525067,0.915,America,American English,London

In [92]:
df.rename(index=str.upper, inplace= True)

In [94]:
df.rename(index=lambda x: x.lower())

,Population,GDP,Surface Area,HDI,Continent,Language,Capital
canada,35.467,1785387,9984670,0.913,America,NaN,Toronto
france,63.951,2833687,640679,0.888,Europe,French,Paris
germany,80.940,3874437,357114,0.916,Europe,German,Berlin
italy,60.665,2167744,301336,0.873,Europe,Italian,Rome
japan,127.061,4602367,377930,0.891,Asia,Japanese,Tokyo
united kingdom,64.511,2950039,242495,0.907,Europe,English,Washington DC
united states,318.523,17348075,9525067,0.915,America,American English,London

---
### Dropping columns

In [ ]:
df.drop(columns='Language', inplace=True)

---
### Adding values

In [122]:
china = pd.DataFrame({
    'Population': [3],
    'GDP': [5]
}, columns= ['Population', 'GDP'])

china
pd.concat([df, china], ignore_index= True)

,index,Population,GDP,Surface Area,HDI,Continent,Language,Capital
0,CANADA,35.467,1785387.0,9984670.0,0.913,America,NaN,Toronto
1,FRANCE,63.951,2833687.0,640679.0,0.888,Europe,French,Paris
2,GERMANY,80.940,3874437.0,357114.0,0.916,Europe,German,Berlin
3,ITALY,60.665,2167744.0,301336.0,0.873,Europe,Italian,Rome
4,JAPAN,127.061,4602367.0,377930.0,0.891,Asia,Japanese,Tokyo
5,UNITED KINGDOM,64.511,2950039.0,242495.0,0.907,Europe,English,Washington DC
6,UNITED STATES,318.523,17348075.0,9525067.0,0.915,America,American English,London
7,NaN,3.000,5.0,NaN,NaN,NaN,NaN,NaN

Append returns a new `DataFrame`:

In [ ]:
df

You can directly set the new index and values to the `DataFrame`:

In [98]:
df.loc['China'] = pd.Series({'Population': 1_400_000_000, 'Continent': 'Asia'})

In [99]:
df

,Population,GDP,Surface Area,HDI,Continent,Language,Capital
CANADA,3.546700e+01,1785387.0,9984670.0,0.913,America,NaN,Toronto
FRANCE,6.395100e+01,2833687.0,640679.0,0.888,Europe,French,Paris
GERMANY,8.094000e+01,3874437.0,357114.0,0.916,Europe,German,Berlin
ITALY,6.066500e+01,2167744.0,301336.0,0.873,Europe,Italian,Rome
JAPAN,1.270610e+02,4602367.0,377930.0,0.891,Asia,Japanese,Tokyo
UNITED KINGDOM,6.451100e+01,2950039.0,242495.0,0.907,Europe,English,Washington DC
UNITED STATES,3.185230e+02,17348075.0,9525067.0,0.915,America,American English,London
China,1.400000e+09,NaN,NaN,NaN,Asia,NaN,NaN

We can use `drop` to just remove a row by index:

In [100]:
df.drop('China', inplace=True)

In [101]:
df

,Population,GDP,Surface Area,HDI,Continent,Language,Capital
CANADA,35.467,1785387.0,9984670.0,0.913,America,NaN,Toronto
FRANCE,63.951,2833687.0,640679.0,0.888,Europe,French,Paris
GERMANY,80.940,3874437.0,357114.0,0.916,Europe,German,Berlin
ITALY,60.665,2167744.0,301336.0,0.873,Europe,Italian,Rome
JAPAN,127.061,4602367.0,377930.0,0.891,Asia,Japanese,Tokyo
UNITED KINGDOM,64.511,2950039.0,242495.0,0.907,Europe,English,Washington DC
UNITED STATES,318.523,17348075.0,9525067.0,0.915,America,American English,London

---
### More radical index changes

In [106]:
df.reset_index(inplace= True)

In [107]:
df

,index,Population,GDP,Surface Area,HDI,Continent,Language,Capital
0,CANADA,35.467,1785387.0,9984670.0,0.913,America,NaN,Toronto
1,FRANCE,63.951,2833687.0,640679.0,0.888,Europe,French,Paris
2,GERMANY,80.940,3874437.0,357114.0,0.916,Europe,German,Berlin
3,ITALY,60.665,2167744.0,301336.0,0.873,Europe,Italian,Rome
4,JAPAN,127.061,4602367.0,377930.0,0.891,Asia,Japanese,Tokyo
5,UNITED KINGDOM,64.511,2950039.0,242495.0,0.907,Europe,English,Washington DC
6,UNITED STATES,318.523,17348075.0,9525067.0,0.915,America,American English,London

In [108]:
df.set_index('Population')

,index,GDP,Surface Area,HDI,Continent,Language,Capital
Population,,,,,,,
35.467,CANADA,1785387.0,9984670.0,0.913,America,NaN,Toronto
63.951,FRANCE,2833687.0,640679.0,0.888,Europe,French,Paris
80.940,GERMANY,3874437.0,357114.0,0.916,Europe,German,Berlin
60.665,ITALY,2167744.0,301336.0,0.873,Europe,Italian,Rome
127.061,JAPAN,4602367.0,377930.0,0.891,Asia,Japanese,Tokyo
64.511,UNITED KINGDOM,2950039.0,242495.0,0.907,Europe,English,Washington DC
318.523,UNITED STATES,17348075.0,9525067.0,0.915,America,American English,London

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Creating columns from other columns

Altering a DataFrame often involves combining different columns into another. For example, in our Countries analysis, we could try to calculate the "GDP per capita", which is just, `GDP / Population`.

In [123]:
df[['Population', 'GDP']]

   Population         GDP
0      35.467   1785387.0
1      63.951   2833687.0
2      80.940   3874437.0
3      60.665   2167744.0
4     127.061   4602367.0
5      64.511   2950039.0
6     318.523  17348075.0

The regular pandas way of expressing that, is just dividing each series:

In [124]:
df['GDP'] / df['Population']

0    50339.385908
1    44310.284437
2    47868.013343
3    35733.025633
4    36221.712406
5    45729.239975
6    54464.120330
dtype: float64

The result of that operation is just another series that you can add to the original `DataFrame`:

In [125]:
df['GDP Per Capita'] = df['GDP'] / df['Population']

In [130]:
df['Population_in_millions'] = df['Population'] * 1_000_000

df

,index,Population,GDP,Surface Area,HDI,Continent,Language,Capital,GDP Per Capita,Population_in_millions
0,CANADA,35.467,1785387.0,9984670.0,0.913,America,NaN,Toronto,50339.385908,35467000.0
1,FRANCE,63.951,2833687.0,640679.0,0.888,Europe,French,Paris,44310.284437,63951000.0
2,GERMANY,80.940,3874437.0,357114.0,0.916,Europe,German,Berlin,47868.013343,80940000.0
3,ITALY,60.665,2167744.0,301336.0,0.873,Europe,Italian,Rome,35733.025633,60665000.0
4,JAPAN,127.061,4602367.0,377930.0,0.891,Asia,Japanese,Tokyo,36221.712406,127061000.0
5,UNITED KINGDOM,64.511,2950039.0,242495.0,0.907,Europe,English,Washington DC,45729.239975,64511000.0
6,UNITED STATES,318.523,17348075.0,9525067.0,0.915,America,American English,London,54464.120330,318523000.0

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Statistical info

You've already seen the `describe` method, which gives you a good "summary" of the `DataFrame`. Let's explore other methods in more detail:

In [131]:
df.head()

,index,Population,GDP,Surface Area,HDI,Continent,Language,Capital,GDP Per Capita,Population_in_millions
0,CANADA,35.467,1785387.0,9984670.0,0.913,America,NaN,Toronto,50339.385908,35467000.0
1,FRANCE,63.951,2833687.0,640679.0,0.888,Europe,French,Paris,44310.284437,63951000.0
2,GERMANY,80.940,3874437.0,357114.0,0.916,Europe,German,Berlin,47868.013343,80940000.0
3,ITALY,60.665,2167744.0,301336.0,0.873,Europe,Italian,Rome,35733.025633,60665000.0
4,JAPAN,127.061,4602367.0,377930.0,0.891,Asia,Japanese,Tokyo,36221.712406,127061000.0

In [145]:
df.describe(include= 'all')

,index,Population,GDP,Surface Area,HDI,Continent,Language,Capital,GDP Per Capita,Population_in_millions
count,7,7.000000,7.000000e+00,7.000000e+00,7.000000,7,6,7,7.000000,7.000000e+00
unique,7,NaN,NaN,NaN,NaN,3,6,7,NaN,NaN
top,CANADA,NaN,NaN,NaN,NaN,Europe,French,Toronto,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,4,1,1,NaN,NaN
mean,NaN,107.302571,5.080248e+06,3.061327e+06,0.900429,NaN,NaN,NaN,44952.254576,1.073026e+08
std,NaN,97.249970,5.494020e+06,4.576187e+06,0.016592,NaN,NaN,NaN,6954.983875,9.724997e+07
min,NaN,35.467000,1.785387e+06,2.424950e+05,0.873000,NaN,NaN,NaN,35733.025633,3.546700e+07
25%,NaN,62.308000,2.500716e+06,3.292250e+05,0.889500,NaN,NaN,NaN,40265.998421,6.230800e+07
50%,NaN,64.511000,2.950039e+06,3.779300e+05,0.907000,NaN,NaN,NaN,45729.239975,6.451100e+07
75%,NaN,104.000500,4.238402e+06,5.082873e+06,0.914000,NaN,NaN,NaN,49103.699626,1.040005e+08
max,NaN,318.523000,1.734808e+07,9.984670e+06,0.916000,NaN,NaN,NaN,54464.120330,3.185230e+08

In [133]:
population = df['Population']

In [134]:
population.min(), population.max()

(35.467, 318.523)

In [135]:
population.sum()

751.118

In [136]:
population.sum() / len(population)

107.30257142857144

In [137]:
population.mean()

107.30257142857144

In [138]:
population.std()

97.24996987121581

In [139]:
population.median()

64.511

In [140]:
population.describe()

count      7.000000
mean     107.302571
std       97.249970
min       35.467000
25%       62.308000
50%       64.511000
75%      104.000500
max      318.523000
Name: Population, dtype: float64

In [141]:
population.quantile(.25)

62.308

In [142]:
population.quantile([.2, .4, .6, .8, 1])

0.2     61.3222
0.4     64.1750
0.6     74.3684
0.8    117.8368
1.0    318.5230
Name: Population, dtype: float64

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Exercise

Part 1: Create the DataFrame

Create a DataFrame called `students_df` using this data:

| Name   | Age | Gender | Score | Passed |
| ------ | --- | ------ | ----- | ------ |
| Aisha  | 20  | F      | 78    | True   |
| Tunde  | 22  | M      | 45    | False  |
| Sola   | 19  | F      | 88    | True   |
| Kunle  | 21  | M      | 60    | True   |
| Zainab | 23  | F      | 39    | False  |

Task 1

1. Import pandas
2. Create the DataFrame from a dictionary
3. Print the DataFrame

Part 2: Indexing & Column Selection

Task 2

1. Print only the `Name` column
2. Print the `Name` and `Score` columns
3. Print the first 3 rows using:

   * `.head()`
   * `.iloc[]`

Part 3: Row Selection & Slicing

Task 3

1. Print the row for **Sola** using:

   * `.loc[]`
2. Print rows 1 to 3 using:

   * `.iloc[]`
3. Print all rows where `Score` is greater than 60

Part 4: Adding & Modifying Columns

Task 4

1. Add a new column called `Bonus`:

   * Bonus = 5 points for students who passed
   * Bonus = 0 points for students who failed
2. Create a new column `Final_Score`:

   * Final_Score = Score + Bonus
3. Print the updated DataFrame